name: Build Debian arm64 rootfs

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y debootstrap xz-utils qemu-user-static binfmt-support

      - name: Build Debian bookworm rootfs
        run: |
          mkdir rootfs
          sudo debootstrap --arch=arm64 --include=apt,ca-certificates,systemd-sysv bookworm rootfs http://deb.debian.org/debian/

      - name: Package rootfs
        run: |
          sudo tar -cJf debian-bookworm-arm64-rootfs.tar.xz -C rootfs .
          sudo chown runner:runner debian-bookworm-arm64-rootfs.tar.xz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-rootfs
          path: debian-bookworm-arm64-rootfs.tar.xz